version: '3.8'

services:
  sync:
    image: victorrds/etebase:alpine
    container_name: "etebase_sync"
    volumes:
      - ./etebase_data:/data:rw
      - ./etebase_static:${STATIC_PATH}:rw
    environment:
      SERVER: asgi
      SUPER_USER: ${ADMIN_USER}
      SUPER_PASS: ${ADMIN_PASS}
      DB_ENGINE: postgres
      DATABASE_NAME: ${DB_NAME}
      DATABASE_USER: ${DB_USER}
      DATABASE_PASSWORD: ${DB_PASS}
      DATABASE_HOST: db
    ports:
      - 3735:3735
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:13
    container_name: "etebase_db"
    volumes:
      - etebase_db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    restart: unless-stopped

  web:
    build: .
    container_name: "etebase_web"
    ports:
      - 8020:8000
    restart: unless-stopped

volumes:
        #  etebase_data:
        #    external: true
        #  etebase_static:
        #    external: true
  etebase_db:
    external: true
