version: "3.8"

services:
  db:
    image: postgres
    container_name: "postgresql"
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgresql:/var/lib/postgresql/data
  
  adminer:
    image: adminer
    container_name: "postgresql_adminer"
    restart: always
    ports: 
      - 8070:8080

volumes:
  postgresql:
    external: true
