---

- hosts: dev_servers
  remote_user: "{{ user.name }}"
  become: yes
  become_method: sudo

  roles:
    - mount
    - packages
    - users
    - dotfiles
    - restore
    - containers
    - cronjobs
    - nginx
