---

- name: Add Docker’s official GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add stable Docker repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    state: present

- name: Install Docker Engine
  apt:
    update_cache: yes
    name: "{{ item }}"
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Install Docker Compose
  ansible.builtin.get_url:
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-{{ ansible_facts.system }}-{{ ansible_architecture }}
    dest: /usr/local/bin/docker-compose

- name: Give executable permission to docker-compose binary
  ansible.builtin.file:
    path: /usr/local/bin/docker-compose
    mode: +x

      #- name: Create symbolic link 
      #  file:
      #    src: /usr/local/bin/docker-compose
      #    dest: /usr/bin/docker-compose
      #    state: link
