---
- name: Install neovim
  apt:
    name: neovim
    state: present

- name: Install python3-pip
  apt:
    name: python3-pip
    state: present

- name: Install rsync
  apt:
    name: rsync
    state: present
