version: '3'
services:
  baikal:
    image: ckulka/baikal:latest
    container_name: "baikal"
    ports:
      - "8081:80"
    volumes:
      - baikal_config:/var/www/baikal/config
      - baikal_data:/var/www/baikal/Specific
    restart: unless-stopped

volumes:
  baikal_config:
    external: true
  baikal_data:
    external: true
