version: "3.8"

services:
  bitwardenrs:
    image: bitwardenrs/server:latest
    container_name: "bitwardenrs"
    volumes:
      - bitwarden:/data/
    ports:
      - 8010:80
    environment:
      ADMIN_TOKEN: ${ADMIN_TOKEN}
    restart: unless-stopped

volumes:
  bitwarden:
    external: true
    name: bitwarden
