---

- name: Clone dotfiles repository
  become: no
  ansible.builtin.git:
    repo: https://github.com/memreyagci/dotfiles.git
    dest: "/home/{{ user.name }}/dotfiles"
    clone: yes
    update: yes

- name: Deploy dotfiles
  become: no
  stow:
    state: present
    package: "{{ item }}"
    dir: "/home/{{ user.name }}/dotfiles"
    target: "/home/{{ user.name }}"
  with_items:
    - neovim
    - bash
