---

- name: Clone dotfiles repository
  ansible.builtin.git:
    repo: https://github.com/memreyagci/dotfiles.git
    dest: "/home/{{ USER.NAME }}/dotfiles"
    clone: yes
    update: yes

- name: Deploy dotfiles
  stow:
    state: present
    package: "{{ item }}"
    dir: "/home/{{ USER.NAME }}/dotfiles"
    target: "/home/{{ USER.NAME }}"
  with_items:
    - neovim
    - bash
