version: "3.3"

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: "vaultwarden"
    volumes:
      - vaultwarden:/data/
    ports:
      - 8010:80
    environment:
      ADMIN_TOKEN: ${ADMIN_TOKEN}
    restart: unless-stopped

volumes:
  vaultwarden:
    external: true
