---

- name: Create a Baikal container
  community.docker.docker_container:
    name: 'baikal'
    image: 'ckulka/baikal:latest'
    recreate: true
    restart_policy: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.baikal.rule: "Host(`{{ BAIKAL_DOMAIN }}`)"
      traefik.http.routers.baikal.entrypoints: "websecure"
      traefik.http.routers.baikal.tls.certresolver: "myresolver"
    volumes:
      - "baikal_config:/var/www/baikal/config"
      - "baikal_data:/var/www/baikal/Specific"
