---

- name: Clone a turtl/server repository
  git:
    repo: https://github.com/turtl/server.git
    dest: /tmp/turtl
    clone: yes
    update: yes

- name: Build an image for Turtl
  community.docker.docker_image:
    build:
      path: /tmp/turtl
    name: 'turtl/server'
    source: build

- name: Create a Turtl container
  community.docker.docker_container:
    name: 'turtl_server'
    image: 'turtl/server'
    recreate: true
    restart_policy: unless-stopped
    ports:
      - "8040:8181"
    env:
      TURTL_DB_HOST: postgres-db
      TURTL_DB_PORT: "5432"
      TURTL_DB_DATABASE: turtl
      TURTL_DB_USER: turtl
      TURTL_DB_PASSWORD: "{{ turtl.db_password }}"
      TURTL_APP_SECURE_HASH_SALT: "{{ turtl.app_secure_hash_salt }}"
      TURTL_APP_API_URL: "{{ turtl.domain }}"

- name: Create a PostgreSQL container for Turtl
  community.docker.docker_container:
    name: 'turtl_db'
    image: 'postgres:11-alpine'
    recreate: true
    volumes:
      - "turtl:/var/lib/postgresql/"
    env:
      POSTGRES_PASSWORD: "{{ turtl.db_password }}"
      POSTGRES_USER: turtl
      POSTGRES_DB: turtl
