---

- name: Clone Umami repository
  ansible.builtin.git:
    repo: https://github.com/mikecao/umami
    dest: "/home/{{ user.name }}/umami"
    clone: yes
    update: no

- name: Create Umami containers
  community.docker.docker_compose:
    project_name: "umami"
    definition:
      version: '3'
      services:
        umami:
          container_name: "umami_server"
          image: ghcr.io/mikecao/umami:postgresql-latest
          ports:
            - "8050:3000"
          environment:
            DATABASE_URL: "postgresql://{{ umami.db.user }}:{{ umami.db.password }}@db:5432/umami"
            DATABASE_TYPE: postgresql
            HASH_SALT: "{{ umami.hash_salt }}"
          depends_on:
            - db
          restart: unless-stopped
        db:
          container_name: "umami_db"
          image: postgres:12-alpine
          environment:
            POSTGRES_DB: "umami"
            POSTGRES_USER: "{{ umami.db.user }}"
            POSTGRES_PASSWORD: "{{ umami.db.password }}"
          volumes:
            - "/home/{{ user.name }}/umami/sql/schema.postgresql.sql:/docker-entrypoint-initdb.d/schema.postgresql.sql:ro"
            - "umami-db:/var/lib/postgresql/data"
          restart: unless-stopped

      volumes:
        umami-db:
