version: "3"

services:
  ghost:
    image: ghost
    container_name: "ghost"
    volumes:
      - ghost:/var/lib/ghost/content
    ports:
      - 3001:2368
    environment:
      url: "https://www.meyagci.xyz"
    restart: unless-stopped

volumes:
  ghost:
    external: true
